import { Assessment, PatientDetails, CephalometricInput, OciResult, AdvancedClinicalIntelligence } from '../types';
import { calculateOCI } from '../scoringEngine';

// Demo Patient 1: Skeletal Class I
const input1: CephalometricInput = {
  anb: 2.2,
  sna: 82.1,
  snb: 79.9,
  wits: 0.2,
  snMp: 32.5,
  fma: 25.0,
  u1Sn: 104.2,
  u1NaDeg: 22.1,
  u1NaMm: 4.1,
  impa: 90.1,
  l1NbDeg: 25.2,
  l1NbMm: 4.2,
  interincisalAngle: 135.5,
  overjet: 2.5,
  overbite: 2.4,
  upperLipELine: -1.8,
  lowerLipELine: 0.1,
  nasolabialAngle: 102.5,
  facialConvexity: 12.1,
  molarRelation: 'Class I',
  canineRelation: 'Class I',
  crossbite: 'None',
  deepBite: 0,
  openBite: 0,
  curveOfSpee: 0,
  midlineDeviation: 0,
  posteriorCrossbite: 'None',
  archWidthDifference: 0,
  dentalMidlineDev: 0
};

const oci1 = calculateOCI(input1);
const details1: PatientDetails = {
  name: 'Marcus Vance',
  age: 14,
  gender: 'Male',
  caseNumber: 'OCI-DEMO-001',
  diagnosis: 'Class I',
  date: '2026-07-02',
  facialProfile: 'Straight',
  smileAnalysis: 'Consonant',
  crowdingSpacing: 'Crowding',
  clinicalNotes: '14-year-old male with mild dental crowding and an aesthetic, straight soft-tissue facial profile. Skeletal parameters demonstrate an ideal Class I skeletal relationship (ANB: 2.2°) and average vertical growth pattern.'
};

const advanced1: AdvancedClinicalIntelligence = {
  cvmStage: 'CS4',
  growthStatus: 'Deceleration',
  skeletalMaturity: 'Post-Peak Growth',
  extractionRecommendation: 'No',
  extractionProbability: '5%',
  extractionReason: 'Arch length discrepancy is mild (< 3mm) and incisor positioning is well within the envelope of balance. Crowding can be resolved with conservative alignment and interproximal reduction (IPR).',
  surgeryRecommendation: 'No',
  surgeryProbability: '0%',
  surgeryReason: 'Skeletal Class I relationship with balanced skeletal and dental jaw relations. Surgery is not indicated.',
  anchorageRequirement: 'Minimum',
  suggestedAnchorage: 'Passive alignment, standard molar stops',
  difficultyScore: '18',
  complexity: 'Simple',
  estimatedDuration: '12-14 Months',
  estimatedAppointments: '10',
  estimatedRetention: 'Standard fixed lingual retainers 3-3 with nightly Essix cover',
  relapseRisk: 'Low',
  relapseProbability: '15%',
  relapseReason: 'Stable Class I intercuspation serves as natural functional retention. Guard against minor lower incisor rotational relapse.',
  ociSkeletalContribution: '25%',
  ociDentalContribution: '55%',
  ociSoftTissueContribution: '20%',
  ociScoreExplanation: 'The low OCI Score (8) indicates harmonious skeletal alignment. The minor contribution is purely due to mild dental leveling and rotational adjustments.',
  diagnosticConfidence: '98%',
  treatmentConfidence: '95%',
  borderlineCategory: 'None',
  borderlineReason: 'Clear-cut non-extraction therapy with excellent prognosis.',
  skeletalProblems: 'None. Harmonic sagittal and vertical relationship.',
  dentalProblems: 'Mild mandibular anterior crowding (approx 2.5mm); minor rotations of upper lateral incisors.',
  softTissueProblems: 'None. Balanced facial profile with pleasing nasolabial alignment.',
  functionalProblems: 'None. Consonant smile line.',
  primaryObjectives: 'Achieve perfect dental alignment, restore dental midline harmony, maintain current straight facial profile and Class I relationship.',
  secondaryObjectives: 'Establish optimal functional overbite and overjet guides.',
  longTermObjectives: 'Maintain long-term dental alignment and arch coordination with strict compliance on retention.',
  treatmentSequence: '1. Fixed appliance bonding / Aligners sequencing -> 2. Leveling and alignment using light NiTi wires -> 3. Final detailing and settling -> 4. Retention.',
  contraindications: 'Avoid premolar extractions (would cause profile flattening and unneeded spacing).',
  contraindicationReason: 'Extracting in Class I with mild crowding leads to dental collapse and unpleasing soft-tissue retrusion.',
  primaryPlanOption: 'Non-extraction orthodontic alignment with standard orthodontic bracket or clear aligners, paired with minor interproximal reduction (IPR).',
  alternativePlan1: 'Arch expansion using passive self-ligating brackets to resolve crowding without IPR.',
  alternativePlan2: 'No treatment (cosmetic observation).',
  overallPrognosis: 'Excellent',
  skeletalCorrectionPotential: 'Stable (no correction required)',
  dentalCorrectionPotential: 'Excellent (complete resolution of crowding expected)',
  softTissueImprovement: 'Maintained (ideal aesthetics preserved)',
  longTermStability: 'Excellent with bonded lingual retainers',
  successProbability: '98%',
  explanationWhy: 'Highly compliant age group with ideal biological response, zero skeletal discrepancies, and mild crowding.',
  decisionTrace: 'Class I skeletal -> Mild crowding -> Non-extraction pathway.',
  riskAlerts: 'No significant risks identified. Normal risk of root resorption and decalcification if hygiene is poor.',
  finalClinicalSummary: '1. Chief Diagnosis: Skeletal Class I, Average growth pattern, Mild crowding. 2. Etiology: Minor dental-arch discrepancy. 3. Growth Status: CS4 (Post-Peak). 4. OCI Severity: Minimal (8). 5. Recommended Treatment: Clear aligners or fixed braces, non-extraction. 6. Prognosis: Excellent.'
};

const demo1: Assessment = {
  id: 'OCI-DEMO-001',
  patientDetails: details1,
  cephalometricInput: input1,
  ociResult: oci1,
  aiSummary: 'Ideal skeletal Class I patient with mild dental crowding. Non-extraction orthodontic alignment is the primary treatment of choice.',
  createdAt: '2026-07-02T06:00:00.000Z',
  advanced: advanced1
};


// Demo Patient 2: Skeletal Class II Division 1
const input2: CephalometricInput = {
  anb: 6.5,
  sna: 82.5,
  snb: 76.0,
  wits: 4.8,
  snMp: 31.8,
  fma: 24.5,
  u1Sn: 114.5,
  u1NaDeg: 29.8,
  u1NaMm: 6.8,
  impa: 98.2,
  l1NbDeg: 29.5,
  l1NbMm: 6.5,
  interincisalAngle: 119.2,
  overjet: 6.8,
  overbite: 4.5,
  upperLipELine: 0.5,
  lowerLipELine: 2.5,
  nasolabialAngle: 93.5,
  facialConvexity: 18.2,
  molarRelation: 'Class II',
  canineRelation: 'Class II',
  crossbite: 'None',
  deepBite: 4.5,
  openBite: 0,
  curveOfSpee: 3.0,
  midlineDeviation: 1.0,
  posteriorCrossbite: 'None',
  archWidthDifference: 0,
  dentalMidlineDev: 0
};

const oci2 = calculateOCI(input2);
const details2: PatientDetails = {
  name: 'Clara Sterling',
  age: 11,
  gender: 'Female',
  caseNumber: 'OCI-DEMO-002',
  diagnosis: 'Class II',
  date: '2026-07-02',
  facialProfile: 'Convex',
  smileAnalysis: 'Gummy',
  crowdingSpacing: 'Crowding',
  clinicalNotes: '11-year-old female presenting with Skeletal Class II Division 1 malocclusion. Marked mandibular retrusion (SNB: 76.0°) and proclined upper incisors (U1-SN: 114.5°) with an increased overjet of 6.8mm and convex facial profile. Currently in pre-peak growth stage (CVM CS3).'
};

const advanced2: AdvancedClinicalIntelligence = {
  cvmStage: 'CS3',
  growthStatus: 'Acceleration',
  skeletalMaturity: 'Pre-Peak Growth (Peak Impending)',
  extractionRecommendation: 'No (Growth Modification First)',
  extractionProbability: '25%',
  extractionReason: 'Patient has outstanding growth potential (CVM CS3). Growth modification via functional orthopedic appliances is highly indicated to advance the retruded mandible, avoiding the necessity of extraction camouflage or future surgery.',
  surgeryRecommendation: 'No',
  surgeryProbability: '5%',
  surgeryReason: 'Patient is growing. Orthognathic surgery is contraindicated at this age and highly unlikely to be needed if growth modification is successful.',
  anchorageRequirement: 'Moderate',
  suggestedAnchorage: 'Functional appliance (Twin Block or Herbst), followed by transpalatal arch (TPA) for torque control',
  difficultyScore: '42',
  complexity: 'Moderate',
  estimatedDuration: '18-24 Months (Two-phase therapy)',
  estimatedAppointments: '22',
  estimatedRetention: 'Upper and lower bonded lingual retainers paired with a nocturnal Hawley retainer or activator',
  relapseRisk: 'Moderate',
  relapseProbability: '40%',
  relapseReason: 'Risk of post-treatment mandibular relapse if growth is not fully settled or functional appliance wear was inconsistent.',
  ociSkeletalContribution: '45%',
  ociDentalContribution: '35%',
  ociSoftTissueContribution: '20%',
  ociScoreExplanation: 'The moderate OCI score (38) is driven by skeletal Class II mandibular deficiency combined with labial flaring of the maxillary incisors.',
  diagnosticConfidence: '95%',
  treatmentConfidence: '90%',
  borderlineCategory: 'Functional modification vs. Camouflage',
  borderlineReason: 'If patient compliance with functional appliances is poor, treatment must pivot to therapeutic orthodontic camouflage with upper premolar extractions.',
  skeletalProblems: 'Skeletal Class II sagittal pattern driven by mandibular skeletal retrusion; normal maxilla; average vertical growth direction.',
  dentalProblems: 'Class II Division 1 dental relationship, severe overjet (6.8mm), deep bite (4.5mm), dental crowding, deep Curve of Spee.',
  softTissueProblems: 'Convex facial profile, lower lip trapped behind upper incisors (lip trap), short chin-neck distance.',
  functionalProblems: 'Lip incompetence, gummy smile.',
  primaryObjectives: 'Promote mandibular skeletal advancement during the growth peak, reduce overjet and deep overbite, relieve dental crowding, correct lip trap and achieve competent lip seal.',
  secondaryObjectives: 'Level the Curve of Spee, align dental arches, settle buccal intercuspation into Class I.',
  longTermObjectives: 'Ensure stable mandibular position and facial harmony through growth completion.',
  treatmentSequence: 'Phase 1: Twin Block functional orthopedic appliance wear for 9-12 months -> Phase 2: Comprehensive fixed braces (brackets) for 12 months to level, align, detail, and settle.',
  contraindications: 'Do not extract maxillary teeth in the initial stage. Avoid orthognathic surgery until growth is complete if modification fails.',
  contraindicationReason: 'Extractions are unneeded because mandibular growth can resolve the overjet. Surgery is biologically contraindicated in active growing children.',
  primaryPlanOption: 'Two-phase orthopedic-orthodontic therapy: Phase 1 Twin Block appliance for mandibular skeletal advancement, Phase 2 full fixed brackets.',
  alternativePlan1: 'Late orthodontic camouflage using upper first premolar extractions and maximum anchorage to retract the upper anterior teeth (pivoted if growth is complete).',
  alternativePlan2: 'No orthopedic intervention; watch and wait for adult surgical advancement (high risk of poor psychological impact on the child).',
  overallPrognosis: 'Very Good',
  skeletalCorrectionPotential: 'Excellent (CVM CS3 is the optimal time for skeletal modification)',
  dentalCorrectionPotential: 'Very Good (overjet and deep bite resolved)',
  softTissueImprovement: 'Significant improvement in profile convexity and chin projection',
  longTermStability: 'Good with rigid long-term active retention',
  successProbability: '92%',
  explanationWhy: 'Perfect timing relative to peak growth velocity. Twin Block appliance is highly reliable in compliant patients.',
  decisionTrace: 'Growing Class II mandibular retrusion -> Twin Block functional orthopedic pathway.',
  riskAlerts: 'Patient compliance with functional appliances is critical; lack of wear results in failure of skeletal correction. Monitor for dental tipping.',
  finalClinicalSummary: '1. Chief Diagnosis: Skeletal Class II Div 1, Mandibular retrusion, Active growth. 2. Etiology: Skeletal-driven retrognathia. 3. Growth Status: CS3 (Pre-Peak). 4. OCI Severity: Moderate (38). 5. Recommended Treatment: Phase 1 Twin Block, Phase 2 fixed braces. 6. Prognosis: Very Good.'
};

const demo2: Assessment = {
  id: 'OCI-DEMO-002',
  patientDetails: details2,
  cephalometricInput: input2,
  ociResult: oci2,
  aiSummary: 'Skeletal Class II Division 1 patient with significant mandibular retrognathia. Excellent candidate for Phase I growth modification using functional orthopedic appliances.',
  createdAt: '2026-07-02T06:01:00.000Z',
  advanced: advanced2
};


// Demo Patient 3: Skeletal Class III
const input3: CephalometricInput = {
  anb: -4.2,
  sna: 78.5,
  snb: 82.7,
  wits: -7.5,
  snMp: 33.1,
  fma: 26.2,
  u1Sn: 121.2,
  u1NaDeg: 34.5,
  u1NaMm: 8.5,
  impa: 78.4,
  l1NbDeg: 16.2,
  l1NbMm: 1.5,
  interincisalAngle: 116.8,
  overjet: -4.5,
  overbite: -1.5,
  upperLipELine: -4.5,
  lowerLipELine: 3.5,
  nasolabialAngle: 112.4,
  facialConvexity: 2.2,
  molarRelation: 'Class III',
  canineRelation: 'Class III',
  crossbite: 'Anterior',
  deepBite: 0,
  openBite: 1.5,
  curveOfSpee: 1.0,
  midlineDeviation: 2.5,
  posteriorCrossbite: 'None',
  archWidthDifference: 4.0,
  dentalMidlineDev: 2.0
};

const oci3 = calculateOCI(input3);
const details3: PatientDetails = {
  name: 'Viktor Thorne',
  age: 22,
  gender: 'Male',
  caseNumber: 'OCI-DEMO-003',
  diagnosis: 'Class III',
  date: '2026-07-02',
  facialProfile: 'Concave',
  smileAnalysis: 'Flat',
  crowdingSpacing: 'Crowding',
  clinicalNotes: '22-year-old adult male displaying a severe Skeletal Class III relationship (ANB: -4.2°, Wits: -7.5mm) driven by a combination of maxillary retrusion (SNA: 78.5°) and mandibular prognathism (SNB: 82.7°). Dental compensations are extreme: proclined upper incisors (U1-SN: 121.2°) and retroclined lower incisors (IMPA: 78.4°). Presents with anterior crossbite and open bite.'
};

const advanced3: AdvancedClinicalIntelligence = {
  cvmStage: 'CS6',
  growthStatus: 'Growth Complete',
  skeletalMaturity: 'Mature (No Growth Remaining)',
  extractionRecommendation: 'No (Presurgical Decompensation Instead)',
  extractionProbability: '10%',
  extractionReason: 'Treatment requires surgical decompensation. Extracting teeth to camouflage this severe skeletal Class III would lead to poor facial aesthetics and instability. Teeth must be moved into their true relationship relative to their respective jawbone to allow surgical correction.',
  surgeryRecommendation: 'Yes',
  surgeryProbability: '95%',
  surgeryReason: 'The severe skeletal Class III discrepancy (ANB: -4.2°, Wits: -7.5mm) in a fully mature adult (CVM CS6) is far beyond the limits of orthodontic camouflage. Combined orthognathic surgery (LeFort I maxillary advancement and BSSO mandibular setback) is mandatory for functional and aesthetic correction.',
  anchorageRequirement: 'Maximum / Absolute',
  suggestedAnchorage: 'Mini-screws (TADs) or surgical fixation plates to facilitate presurgical decompensation',
  difficultyScore: '78',
  complexity: 'Complex / Surgical',
  estimatedDuration: '24-30 Months (Surgical Timeline)',
  estimatedAppointments: '32',
  estimatedRetention: 'Permanent upper and lower bonded lingual retainers, paired with heavy-duty nocturnal thermoformed retainers',
  relapseRisk: 'High (Skeletal & Dental)',
  relapseProbability: '55%',
  relapseReason: 'Class III surgical cases have high potential for late mandibular growth relapse or dental uprighting relapse if post-treatment retention is neglected.',
  ociSkeletalContribution: '50%',
  ociDentalContribution: '35%',
  ociSoftTissueContribution: '15%',
  ociScoreExplanation: 'The high OCI Score (78) is a direct reflection of severe skeletal jaw imbalance combined with extreme compensatory dentoalveolar tipping (U1 proclined, L1 retroclined).',
  diagnosticConfidence: '98%',
  treatmentConfidence: '95%',
  borderlineCategory: 'Surgical Correction vs. Extreme Camouflage',
  borderlineReason: 'There is zero possibility for cosmetic orthodontic camouflage; attempting camouflage would compromise the periodontal support of the lower incisors and worsen the flat-to-concave profile.',
  skeletalProblems: 'Severe Skeletal Class III sagittal disharmony, maxilla retrognathic, mandible prognathic, average-to-long vertical growth vector.',
  dentalProblems: 'Class III dental relationship, anterior crossbite with reverse overjet (-4.5mm), anterior open bite, dental midline deviation, severe maxillary and mandibular crowding.',
  softTissueProblems: 'Concave profile, deficient midface (malar flatting), prominent chin, lower lip protruding beyond upper lip.',
  functionalProblems: 'Difficulty chewing and speaking, anterior tooth wear, temporomandibular joint (TMJ) clicking.',
  primaryObjectives: 'Align arches and reverse dental compensations (decompensation), surgically advance maxilla (LeFort I) and setback mandible (BSSO) to achieve ideal skeletal Class I relationship, restore facial profile harmony and lip competence.',
  secondaryObjectives: 'Correct anterior crossbite, establish ideal overjet and overbite, align midlines.',
  longTermObjectives: 'Ensure stable surgical results, preserve periodontal health, and optimize masticatory function.',
  treatmentSequence: '1. Presurgical orthodontic alignment & decompensation (aligning teeth inside their respective bases, which temporarily worsens the crossbite) -> 2. Virtual surgical planning & splint fabrication -> 3. Combined orthognathic surgery -> 4. Postsurgical orthodontic settling and intercuspation settling -> 5. Long-term fixed retention.',
  contraindications: 'Avoid orthodontic camouflage by tipping the upper incisors further forward or lower incisors further back. Orthopedic appliances like facemasks are contraindicated.',
  contraindicationReason: 'Tipping teeth beyond biological boundaries leads to bone fenestrations and gingival recession. Facemasks will only tip teeth because suture fusion is complete (CVM CS6).',
  primaryPlanOption: 'Presurgical orthodontics followed by combined bilateral sagittal split osteotomy (BSSO) mandibular setback and LeFort I maxillary advancement surgery.',
  alternativePlan1: 'Mandibular dental camouflage with lower premolar extractions and TAD-supported lower arch distalization (severely limited, poor facial outcome).',
  alternativePlan2: 'No treatment (patient accepts function and aesthetics with counseling).',
  overallPrognosis: 'Good (Surgical success is highly predictable)',
  skeletalCorrectionPotential: 'Excellent (via surgical osteotomies)',
  dentalCorrectionPotential: 'Excellent (ideal Class I canine & molar relations achieved)',
  softTissueImprovement: 'Dramatic improvement in midface fullness, chin projection, and profile symmetry',
  longTermStability: 'Moderate-to-Good with strict fixed and removable retention',
  successProbability: '88%',
  explanationWhy: 'Requires highly precise multi-disciplinary coordination between the orthodontist and oral maxillofacial surgeon.',
  decisionTrace: 'Adult Class III -> CS6 -> Severe skeletal discrepancy -> Decompensation -> BSSO + LeFort I Orthognathic Surgery.',
  riskAlerts: 'Surgical risks include nerve parasthesia (lower lip numbness), relapse of mandibular setback, and TMJ adaptation problems. Decompensation temporarily worsens aesthetics before surgery.',
  finalClinicalSummary: '1. Chief Diagnosis: Skeletal Class III, Mandibular prognathism, Maxillary retrusion, Growth Complete. 2. Etiology: Combined skeletal sagittal discrepancy. 3. Growth Status: CS6 (Mature). 4. OCI Severity: Difficult/Surgical (78). 5. Recommended Treatment: Combined Orthognathic Surgery. 6. Prognosis: Good.'
};

const demo3: Assessment = {
  id: 'OCI-DEMO-003',
  patientDetails: details3,
  cephalometricInput: input3,
  ociResult: oci3,
  aiSummary: 'Severe skeletal Class III adult patient with significant maxillary hypoplasia and mandibular excess. Combined orthognathic surgery is mandatory.',
  createdAt: '2026-07-02T06:02:00.000Z',
  advanced: advanced3
};

export const DEMO_PATIENTS: Assessment[] = [demo1, demo2, demo3];
